"""add_error

Revision ID: c0b370f3d21a
Revises: b2c1f4a9e3d84a5f9c2e7a1d3b5f6081
Create Date: 2026-08-14 21:05:18.416310

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0b370f3d21a"
down_revision: str | Sequence[str] | None = "b2c1f4a9e3d84a5f9c2e7a1d3b5f6081"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("error", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "error")
    # ### end Alembic commands ###
