apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "app.name" . }}-secrets
stringData:
  DB_NAME: "otus"
  DB_USER: "admin"
  DB_PASS: "adminpass"
  JWT_SECRET: "pAy2lxgk5gKgn3SdtgjxhIpfNXPa8g8oRaQJUO5O0pk"
