apiVersion: 1
contactPoints:
  - orgId: 1
    name: events
    receivers:
      - uid: events-webhook
        type: webhook
        settings:
          url: http://app-notification.default.svc.cluster.local:80/api/v1/notification/alerts/events
          httpMethod: POST
