"""add_idempotency_keys

Revision ID: 44990d2767be
Revises: 3eb8176b1b344ed0808356b037cb6b7a
Create Date: 2026-08-19 18:19:42.685389

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "44990d2767be"
down_revision: str | Sequence[str] | None = "3eb8176b1b344ed0808356b037cb6b7a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idempotency_keys",
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.UniqueConstraint("idempotency_key", "kind", name="uq_idempotency_keys_key_kind"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("idempotency_keys")
    # ### end Alembic commands ###
