apiVersion: v1
kind: Service
metadata:
  name: my-cluster-kafka-exporter
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
    strimzi.io/kind: Kafka
    strimzi.io/name: my-cluster-kafka-exporter
    release: prometheus
spec:
  selector:
    strimzi.io/cluster: my-cluster
    strimzi.io/kind: Kafka
    strimzi.io/name: my-cluster-kafka-exporter
  ports:
    - name: tcp-prometheus
      port: 9404
      targetPort: tcp-prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-cluster-kafka-exporter
  namespace: kafka
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - kafka
  selector:
    matchLabels:
      strimzi.io/cluster: my-cluster
      strimzi.io/kind: Kafka
      strimzi.io/name: my-cluster-kafka-exporter
  endpoints:
    - port: tcp-prometheus
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
