# ! в продакшене файл должен хранится в секретах gitlab, vault или в другом защищенном месте, но не в репе
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-secrets
  namespace: postgres
stringData:
  DB_NAME: "otus-project"
  DB_USER: "dba"
  DB_PASS: "pAy2lxgk5gKgn3SdtgjxhIpfNXPa8g8oRaQJUO5O0pk"
