"""004

Revision ID: 05c746858fbe
Revises: 1bdfac013620
Create Date: 2026-07-23 06:51:53.710078

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05c746858fbe"
down_revision: Union[str, Sequence[str], None] = "1bdfac013620"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password_hash", sa.String(), nullable=False))
    op.add_column("users", sa.Column("real_name", sa.String(), nullable=False))
    op.add_column(
        "users", sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "created_at")
    op.drop_column("users", "real_name")
    op.drop_column("users", "password_hash")
    # ### end Alembic commands ###
