apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "app.name" . }}-secrets
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-9"
    "helm.sh/hook-delete-policy": before-hook-creation
stringData:
  DB_NAME: "otus-project"
  DB_USER: "dba"
  DB_PASS: "pAy2lxgk5gKgn3SdtgjxhIpfNXPa8g8oRaQJUO5O0pk"
  JWT_SECRET: "pJUO5O0pkgn3SdtgjxhIpfNXAy2lxgk5gKaQPa8g8oR"
  SMTP_PASSWORD: "changeme"
