sequenceDiagram
    actor Пользователь
    participant AuthService
    participant ProfileService
    autonumber
    title Диаграмма авторизации, обновления токена

%%    Client->>AuthService: POST /register (username, password)
%%    AuthService-->>Client: 200 OK (access_token, refresh_token)
    Пользователь->>AuthService: POST /login (username, password)
    AuthService-->>Пользователь: 200 OK (access_token, refresh_token)
    Пользователь->>ProfileService: GET /profile (Authorization: Bearer <token>)
    ProfileService-->>Пользователь: 200 OK (requested data)
    Пользователь->>AuthService: POST /refresh (refresh_token) [optional]
    AuthService-->>Пользователь: 200 OK (new access_token)
