sequenceDiagram
    autonumber
    actor User
    participant AuthApp as Auth Service
    participant AnyApp as *Any* Service

    rect rgb(255, 250, 240)
        Note over User, AnyApp: Доступ к сервисам

        User->>AnyApp: GET /profile (Bearer AT)
        alt Токен валиден
            AnyApp-->>User: 200 Данные профиля
        else Токен истек
            AnyApp-->>User: 401 Не авторизован
            User->>AuthApp: POST /refresh (RT)
            AuthApp-->>User: 200 (AT2, RT2)
            User->>AnyApp: POST /profile (Bearer AT2)
            Note over AnyApp: Проверяет AT2 локально
            AnyApp-->>User: 200 Данные профиля
        end
    end
