sequenceDiagram
    autonumber
    actor User
    participant AuthApp as Auth Service
    participant UserApp as User Service
    participant StrategyApp as Strategy Service
    participant PortfolioApp as Portfolio Service
    participant notify as Notification Service

    rect rgb(240, 248, 255)
        Note over User, AuthApp: Регистрация пользователя
        User->>AuthApp: POST /register (username, password, email)
        Note over AuthApp: Сохранение в БД

        Note over AuthApp, PortfolioApp: kafka: user.create
        AuthApp-->>User: 201 Created (AT, RT)

        par Обработка в User Service
            UserApp--)UserApp: Сохранение в БД User Service (UPSERT)
        and Обработка в Strategy Service
            StrategyApp--)StrategyApp: Сохранение в БД Strategy Service (UPSERT)
        and Обработка в Portfolio Service
            PortfolioApp--)PortfolioApp: Сохранение в БД Portfolio Service (UPSERT)
        and Обработка в Notification Service
            notify--)notify: Сохранение в БД Notification Service (UPSERT)
        end
    end

    rect rgb(255, 250, 240)
        Note over User, UserApp: Получение профиля

        User->>UserApp: GET /profile (Bearer AT)
        alt Пользователя нет в БД
            UserApp--)UserApp: Сохранение в БД мини-версии из AT (UPSERT)
        end
        UserApp-->>User: 200 Данные профиля

    end

    rect rgb(255, 250, 240)
        Note over User, UserApp: Обновление профиля

        User->>UserApp: PATCH /profile (Bearer AT), (telegram, age, etc.)

        alt Неуспешная валидация данных
            UserApp-->>User: 400 Bad Request
        else Успешная валидация данных
            alt Пользователя нет в БД
                UserApp--)UserApp: Сохранение в БД мини-версии из JWT (UPSERT)
            end
            UserApp--)UserApp: Обновление полей в БД
        end

        alt Если изменились контакты
            Note over UserApp, notify: kafka: user.contact
            Note over notify: Изменение контакта
        end

        UserApp-->>User: 200 Данные профиля
    end

    rect rgb(240, 248, 255)
        Note over User, AuthApp: Удаление пользователя
        User->>AuthApp: POST /delete (Bearer AT)
        Note over AuthApp: Удаление из БД

        Note over AuthApp, PortfolioApp: kafka: user.delete
        AuthApp-->>User: 204 No content

        par Обработка в User Service
            UserApp--)UserApp: Удаление из БД User Service
        and Обработка в Strategy Service
            StrategyApp--)StrategyApp: Удаление из БД Strategy Service
        and Обработка в Portfolio Service
            PortfolioApp--)PortfolioApp: Удаление из БД Portfolio Service
        and Обработка в Notification Service
            notify--)notify: Удаление из БД Notification Service
        end
    end
